


/* ------------------------ STAMMDATEN ------------------------------------------------------------------------------ */
CREATE TABLE CPO_ORGANISATION (/* for entity at.hafina.coupon.stamm.Organisation*/ 
 ID NUMBER  (9) /* id */,
 NAME VARCHAR2  (50) /* name */,
 EMAIL VARCHAR2  (50) /* email */,
 TEL VARCHAR2  (50) /* tel */,
 STRASSE VARCHAR2  (50) /* strasse */,
 HAUSNUMMER VARCHAR2  (50) /* hausnummer */,
 ORT VARCHAR2  (50) /* ort */,
 POSTLEITZAHL NUMBER  (9) /* postleitzahl */,
 BUNDESLAND VARCHAR2  (50) /* bundesland */,
 LAND VARCHAR2  (50) /* land */,
 STATUS VARCHAR2  (5) /* status */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPO_ORGANISATION_ID ON CPO_ORGANISATION (ID);
CREATE SEQUENCE S_CPT_ORGANISATION START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;


CREATE TABLE CPO_PERSON (/* for entity at.hafina.coupon.stamm.Person*/ 
 ID NUMBER  (9) /* id */,
 TITEL VARCHAR2  (50) /* titel */,
 VORNAME VARCHAR2  (50) /* vorname */,
 NACHNAME VARCHAR2  (50) /* nachname */,
 EMAIL VARCHAR2  (50) /* email */,
 TEL VARCHAR2  (50) /* tel */,
 STRASSE VARCHAR2  (50) /* strasse */,
 HAUSNUMMER VARCHAR2  (50) /* hausnummer */,
 ORT VARCHAR2  (50) /* ort */,
 POSTLEITZAHL NUMBER  (9) /* postleitzahl */,
 BUNDESLAND VARCHAR2  (50) /* bundesland */,
 LAND VARCHAR2  (50) /* land */,
 ORGANISATION NUMBER  (9) /* id */,
 STATUS VARCHAR2  (5) /* status */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPO_PERSON_ID ON CPO_PERSON (ID);
CREATE INDEX I_CPO_PERSON_ORGANISATION ON CPO_PERSON (ORGANISATION);
CREATE SEQUENCE S_CPT_PERSON START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;

CREATE TABLE CPO_PERSONROLLEN (/* for entity at.hafina.coupon.stamm.PersonRolle*/ 
 ID NUMBER  (9) /* id */,
 REF_PERSON NUMBER  (9) /* id */,
 AKTIV VARCHAR2  (5) /* aktiv */,
 ROLEFUNC VARCHAR2  (5) /* roleFunc */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPO_PERSONROLLEN_ID ON CPO_PERSONROLLEN (ID);
CREATE INDEX I_CPO_PERSONROLLEN_REF_PERSON ON CPO_PERSONROLLEN (REF_PERSON);
CREATE SEQUENCE S_CPO_ORGADMIN START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;





/* ----------------- GUTSCHEIN MODUL --------------------------------------------------------------------------- */

CREATE TABLE CPT_GUTSCHEIN (/* for entity at.hafina.coupon.gutschein.Gutschein*/ 
 ID NUMBER  (9) /* id */,
 GUTSCHEINNUMMER NUMBER  (9) /* gutscheinNummer */,
 AUSGABELAND VARCHAR2  (50) /* ausgabeLand */,
 AUSGABEFILIALE VARCHAR2  (50) /* ausgabeFiliale */,
 AUSGABEZEIT DATE /* ausgabeZeit */,
 GUELTIGVON DATE /* gueltigVon */,
 GUELTIGBIS DATE /* gueltigBis */,
 PINSPERREBIS DATE /* pinsperreBis */,
 TYP VARCHAR2  (5) /* typ */,
 MAXGUTHABEN NUMBER  (13, 4) /* maxGuthaben */,
 GUTHABEN NUMBER  (13, 4) /* guthaben */,
 STATUS VARCHAR2  (5) /* status */,
 VERKAUFSSTATUS VARCHAR2  (5) /* verkaufsStatus */,
 REF_ORGANISATION NUMBER  (9) /* id */,
 REF_PERSON NUMBER  (9) /* id */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPT_GUTSCHEIN_ID ON CPT_GUTSCHEIN (ID);
CREATE INDEX I_CPT_GUTSCHEIN_REF_ORGSTN ON CPT_GUTSCHEIN (REF_ORGANISATION);
CREATE INDEX I_CPT_GUTSCHEIN_REF_PERSON ON CPT_GUTSCHEIN (REF_PERSON);
CREATE SEQUENCE S_CPT_GUTSCHEIN START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;

CREATE TABLE CPT_AUFLADUNG (/* for entity at.hafina.coupon.gutschein.Aufladung*/ 
 ID NUMBER  (9) /* id */,
 WERT NUMBER  (13, 4) /* wert */,
 TRANSAKTIONSID VARCHAR2  (50) /* transaktionsId */,
 STATUS VARCHAR2  (5) /* status */,
 REF_PERSON NUMBER  (9) /* id */,
 REF_ORGANISATION NUMBER  (9) /* id */,
 REF_GUTSCHEIN NUMBER  (9) /* id */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPT_AUFLADUNG_ID ON CPT_AUFLADUNG (ID);
CREATE INDEX I_CPT_AUFLADUNG_REF_PERSON ON CPT_AUFLADUNG (REF_PERSON);
CREATE INDEX I_CPT_AUFLADUNG_REF_ORG ON CPT_AUFLADUNG (REF_ORGANISATION);
CREATE INDEX I_CPT_AUFLADUNG_REF_GTSCN ON CPT_AUFLADUNG (REF_GUTSCHEIN);
CREATE SEQUENCE S_CPT_AUFLADUNG START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;




/* ----------------- GUTSCHEIN ORG Services MODUL --------------------------------------------------------------------------- */


    CREATE TABLE CPT_AUFLADUNGSGRUPPE (/* for entity at.hafina.coupon.orggutscheine.Aufladungsgruppe*/ 
 ID NUMBER  (9) /* id */,
 NAME VARCHAR2  (50) /* name */,
 TYOPE VARCHAR2  (5) /* type */,
 WERT NUMBER  (13, 4) /* defaultWert */,
 REF_ORGANISATION NUMBER  (9) /* id */,
 AKTIV VARCHAR2  (5) /* aktiv */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPT_AUFLADUNGSGRUPPE_ID ON CPT_AUFLADUNGSGRUPPE (ID);
CREATE INDEX I_CPT_AUFLADUNGSGRP_REF_ORGSTN ON CPT_AUFLADUNGSGRUPPE (REF_ORGANISATION);
CREATE SEQUENCE S_CPT_AUFLADUNGSGRUPPE START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;


CREATE TABLE CPT_GTSHAUFLDGSGRUPPE (/* for entity at.hafina.coupon.orggutscheine.GutscheinAufldgsgrp*/ 
 ID NUMBER  (9) /* id */,
 AKTIV VARCHAR2  (5) /* aktiv */,
 REF_GUTSCHEIN NUMBER  (9) /* id */,
 REF_AUFLDGSGRP NUMBER  (9) /* id */,
 CREATEDAT DATE /* createdAt */,
 CREATEDBY NUMBER  (9) /* createdBy */,
 MODIFIEDAT DATE /* modifiedAt */,
 MODIFIEDBY NUMBER  (9) /* modifiedBy */
, TCN NUMBER (9) NOT NULL
); 
CREATE UNIQUE INDEX I_CPT_GTSHAUFLDGSGRUPPE_ID ON CPT_GTSHAUFLDGSGRUPPE (ID);
CREATE INDEX I_CPT_GTSHAUFGRP_REF_GUTSCH ON CPT_GTSHAUFLDGSGRUPPE (REF_GUTSCHEIN);
CREATE INDEX I_CPT_GTSHAUFGRP_REF_AUFGRP ON CPT_GTSHAUFLDGSGRUPPE (REF_AUFLDGSGRP);
CREATE SEQUENCE S_CPT_GTSHAUFLDGSGRP START WITH 1 MINVALUE 1 MAXVALUE 999999999 NOCYCLE CACHE 20 ORDER;

